
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SimulationNodeDatum, SimulationLinkDatum } from 'd3';

/**
 * Enum defining the main navigation views of the application.
 */
export enum ViewMode {
  HOME = 'HOME',
  REPO_ANALYZER = 'REPO_ANALYZER',
  ARTICLE_INFOGRAPHIC = 'ARTICLE_INFOGRAPHIC',
  IMAGE_EDITOR = 'IMAGE_EDITOR',
  DEV_STUDIO = 'DEV_STUDIO'
}

/**
 * Extended D3 Node interface supporting clustering.
 */
export interface D3Node extends SimulationNodeDatum {
  /** Unique identifier for the node (usually file path). */
  id: string;
  /** Group ID for color coding (often based on file type or directory depth). */
  group: number;
  /** Display label for the node. */
  label: string;
  /** Distinguishes between a standard file node and a cluster node representing a directory. */
  type?: 'file' | 'cluster'; 
  /** Number of files contained within a cluster (only for type='cluster'). */
  fileCount?: number;        
  /** Original nodes inside this cluster (only for type='cluster'). */
  childNodes?: D3Node[];     
  x?: number;
  y?: number;
  fx?: number | null;
  fy?: number | null;
}

/**
 * Extended D3 Link interface.
 */
export interface D3Link extends SimulationLinkDatum<D3Node> {
  source: string | D3Node;
  target: string | D3Node;
  /** Strength or weight of the link. */
  value: number;
}

/**
 * Represents the graph data structure passed to D3.
 */
export interface DataFlowGraph {
  nodes: D3Node[];
  links: D3Link[];
}

/**
 * Represents a file item from the Git repository tree.
 */
export interface RepoFileTree {
  path: string;
  type: string;
}

/**
 * State object for the DevStudio environment.
 */
export interface DevStudioState {
  repoName: string;
  fileTree: RepoFileTree[];
  graphData: DataFlowGraph;
}

/**
 * Represents a citation or source found during grounding.
 */
export interface Citation {
    uri: string;
    title: string;
}

/**
 * History item for Repository Analysis.
 */
export interface RepoHistoryItem {
  id: string;
  repoName: string;
  imageData: string;
  is3D: boolean;
  style: string;
  date: Date;
}

/**
 * History item for Article Infographics.
 */
export interface ArticleHistoryItem {
    id: string;
    title: string;
    url: string;
    imageData: string;
    citations: Citation[];
    date: Date;
}

/**
 * Represents a project task generated by AI or user.
 */
export interface Task {
  id: string;
  title: string;
  priority: 'high' | 'medium' | 'low';
  dueDate: string; // ISO string YYYY-MM-DD
  completed: boolean;
  createdAt: number;
}

// Global type augmentations
declare global {
  interface AIStudio {
    hasSelectedApiKey: () => Promise<boolean>;
    openSelectKey: () => Promise<void>;
  }

  interface Window {
    aistudio?: AIStudio;
  }
}
