
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SimulationNodeDatum, SimulationLinkDatum } from 'd3';

/**
 * Enum defining the main navigation views of the application.
 */
export enum ViewMode {
  HOME = 'HOME',
  REPO_ANALYZER = 'REPO_ANALYZER',
  ARTICLE_INFOGRAPHIC = 'ARTICLE_INFOGRAPHIC',
  IMAGE_EDITOR = 'IMAGE_EDITOR',
  DEV_STUDIO = 'DEV_STUDIO'
}

/**
 * Extended D3 Node interface supporting clustering.
 */
export interface D3Node extends SimulationNodeDatum {
  /** Unique identifier for the node (usually file path). */
  id: string;
  /** Group ID for color coding (often based on file type or directory depth). */
  group: number;
  /** Display label for the node. */
  label: string;
  /** Distinguishes between a standard file node and a cluster node representing a directory. */
  type?: 'file' | 'cluster'; 
  /** Number of files contained within a cluster (only for type='cluster'). */
  fileCount?: number;        
  /** Original nodes inside this cluster (only for type='cluster'). */
  childNodes?: D3Node[];     
  x?: number;
  y?: number;
  fx?: number | null;
  fy?: number | null;
}

/**
 * Extended D3 Link interface.
 */
export interface D3Link extends SimulationLinkDatum<D3Node> {
  source: string | D3Node;
  target: string | D3Node;
  /** Strength or weight of the link. */
  value: number;
}

/**
 * Represents the graph data structure passed to D3.
 */
export interface DataFlowGraph {
  nodes: D3Node[];
  links: D3Link[];
}

/**
 * Represents a file item from the Git repository tree.
 */
export interface RepoFileTree {
  path: string;
  type: string;
}

/**
 * Represents a dependency from a package manifest file.
 */
export interface DependencyInfo {
  name: string;
  version: string;
  type: 'production' | 'development' | 'peer';
  ecosystem: 'npm' | 'pip' | 'cargo' | 'go';
  securityAlert?: {
    severity: 'critical' | 'high' | 'medium' | 'low';
    description: string;
  };
}

/**
 * State object for the DevStudio environment.
 */
export interface DevStudioState {
  repoName: string;
  fileTree: RepoFileTree[];
  graphData: DataFlowGraph;
}

/**
 * Represents a citation or source found during grounding.
 */
export interface Citation {
    uri: string;
    title: string;
}

/**
 * History item for Repository Analysis.
 */
export interface RepoHistoryItem {
  id: string;
  repoName: string;
  imageData: string;
  is3D: boolean;
  style: string;
  date: Date;
}

/**
 * History item for Article Infographics.
 */
export interface ArticleHistoryItem {
    id: string;
    title: string;
    url: string;
    imageData: string;
    citations: Citation[];
    date: Date;
}

/**
 * Represents a project task generated by AI or user.
 */
export interface Task {
  id: string;
  title: string;
  priority: 'high' | 'medium' | 'low';
  dueDate: string; // ISO string YYYY-MM-DD
  completed: boolean;
  createdAt: number;
}

// ==================== OmniGen Types ====================

/**
 * Grid Layout Configuration for OmniGen dashboards
 */
export const GRID_SYSTEM = {
  COLS: 12,
  ROW_HEIGHT_PX: 100,
  GAP_PX: 24,
};

export enum EditMode {
  SAFE = 'SAFE',
  PRO = 'PRO'
}

export enum VizType {
  TABLE = 'table',
  PIVOT = 'pivot',
  TIME_SERIES = 'time-series',
  FUNNEL = 'funnel',
  COHORT = 'cohort',
  GEO_MAP = 'geo-map',
  SANKEY = 'sankey',
  NETWORK = 'network',
  BAR = 'bar',
  COLUMN = 'column',
  STACKED_BAR = 'stacked-bar',
  SCATTER = 'scatter',
  HISTOGRAM = 'histogram',
  HEATMAP = 'heatmap',
  TREEMAP = 'treemap',
  BOX_PLOT = 'box-plot',
  GAUGE = 'gauge',
  WATERFALL = 'waterfall',
  KPI_CARD = 'kpi-card'
}

export interface SemanticModel {
  entities: { name: string; description: string; likely_keys: string[]; example_fields: string[] }[];
  metrics: { name: string; definition: string; aggregation: string; grain: string; caveats?: string }[];
  dimensions: { name: string; type: string; examples: string[] }[];
  relationships: { from_entity: string; to_entity: string; join_keys: string[]; join_type: string; confidence: number }[];
  kpis: { name: string; metric: string; goal_direction: 'up' | 'down'; target: string; alert_threshold: string }[];
  glossary: { term: string; meaning: string; synonyms: string[] }[];
  quality_flags: { issue: string; impacted_fields: string[]; severity: 'low' | 'medium' | 'high'; suggested_fix: string }[];
  assumptions: { assumption: string; impact: string; confirm_by: string }[];
}

export interface WidgetConfig {
  id: string;
  type: VizType;
  title: string;
  metric?: string;
  dimension?: string;
  secondaryDimension?: string;
  filter?: Record<string, any>;
  w: number;
  h: number;
  x: number;
  y: number;
}

export interface DashboardTemplate {
  id: string;
  name: string;
  category: string;
  archetype: 'Executive' | 'Ops' | 'Analyst';
  description: string;
  widgets: WidgetConfig[];
  difficulty: 'Novice' | 'Intermediate' | 'Pro';
}

export interface AnalysisResult {
  summary: string;
  drivers: string[];
  recommendations: string[];
  sentiment: 'positive' | 'negative' | 'neutral';
  marketContext?: string;
  sources?: { title: string; uri: string }[];
}

// ==================== DashBoardGen Types ====================

export interface Artifact {
  id: string;
  styleName: string;
  html: string;
  originalHtml?: string;
  status: 'streaming' | 'complete' | 'error';
}

export interface Session {
  id: string;
  prompt: string;
  timestamp: number;
  artifacts: Artifact[];
}

export interface ComponentVariation { name: string; html: string; }
export interface LayoutOption { name: string; css: string; previewHtml: string; }

export type Framework = 'vanilla' | 'tailwind' | 'react-mui' | 'bootstrap' | 'foundation';

export interface GenerationSettings {
  framework: Framework;
  dataContext: string;
  autoA11y: boolean;
  autoCharts: boolean;
  autoPersonas: boolean;
}

// ==================== INFOGenius Types ====================

export type AspectRatio = '16:9' | '9:16' | '1:1' | '4:3' | '3:4';
export type ComplexityLevel = 'Elementary' | 'High School' | 'College' | 'Expert';

export type VisualStyle = 
  | 'Default' | 'Minimalist' | 'Realistic' | 'Cartoon' | 'Vintage' | 'Futuristic' 
  | '3D Render' | 'Sketch' | 'Pixel Art' | 'Origami' | 'Watercolor' | 'Neon' 
  | 'Flat Art' | 'Isometric' | 'Low Poly' | 'Pop Art' | 'Steampunk' | 'Ukiyo-e' 
  | 'Graffiti' | 'Noir' | 'Stained Glass' | 'Claymation' | 'Blueprint' 
  | 'Oil Painting' | 'Art Deco' | 'Psychedelic' | 'Papercut';

export type Language = 'English' | 'Spanish' | 'French' | 'German' | 'Mandarin' | 'Japanese' | 'Hindi' | 'Arabic' | 'Portuguese' | 'Russian';
export type ImageQuality = '1K' | '2K' | '4K';

export interface GeneratedImage {
  id: string;
  data: string;
  prompt: string;
  timestamp: number;
  level?: ComplexityLevel;
  style?: VisualStyle;
  language?: Language;
  quality?: ImageQuality;
  aspectRatio?: AspectRatio;
  relatedTopics?: string[];
  facts?: string[];
  audioUrl?: string;
  parentImageId?: string;
  batchId?: string;
}

export interface SearchResultItem {
  title: string;
  url: string;
}

export interface ResearchResult {
  imagePrompt: string;
  facts: string[];
  searchResults: SearchResultItem[];
  suggestions: string[];
}

// Global type augmentations
declare global {
  interface AIStudio {
    hasSelectedApiKey: () => Promise<boolean>;
    openSelectKey: () => Promise<void>;
  }

  interface Window {
    aistudio?: AIStudio;
  }
}
